
#com.xhb.login.enable=true
#com.xhb.login.strategy
# com.xhb.login.name
# com.xhb.login.filePath

#数据库连接信息
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
#mybatis驼峰处理
mybatis.configuration.map-underscore-to-camel-case=true